# Generated by Django 3.0.2 on 2020-02-11 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='row_news',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('news_name', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('news_no', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('author', models.TextField(null=True)),
                ('shortened_title', models.CharField(max_length=100)),
                ('images', models.TextField()),
                ('category', models.CharField(max_length=10)),
                ('keywords', models.CharField(max_length=100)),
            ],
        ),
    ]
