# Generated by Django 3.0.2 on 2020-02-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row_news',
            name='images',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='row_news',
            name='keywords',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='row_news',
            name='shortened_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='row_news',
            unique_together={('news_name', 'news_no')},
        ),
    ]
