# Generated by Django 3.0.2 on 2020-02-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200212_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row_news',
            name='shortened_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
