# Generated by Django 3.0.2 on 2020-02-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200212_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row_news',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='row_news',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='row_news',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='row_news',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
